ServerEvents.recipes(event => { 
    
    event.remove({output: 'createaddition:alternator'})
    event.remove({output: 'createaddition:electric_motor'})
    event.remove({id: 'createaddition:mixing/bioethanol'})
    event.remove({id: 'createaddition:liquid_burning/ethanol'})
    event.remove({output: 'createaddition:electrum_ingot'})
    event.remove({id: 'createaddition:compacting/seed_oil'})
    event.remove({id: 'createaddition:pressing/electrum_ingot'})
    event.remove({type: 'createaddition:rolling'})
    event.remove({id: 'immersiveengineering:metalpress/rod_copper'})
    event.remove({id: 'immersiveengineering:metalpress/rod_gold'})
    event.remove({id: 'immersiveengineering:metalpress/rod_brass'})
    event.remove({id: 'immersiveengineering:metalpress/rod_electrum'})
    event.remove({id: 'immersiveengineering:metalpress/plate_zinc'})
    event.replaceInput({input: 'createaddition:copper_spool'}, 'createaddition:copper_spool', 'electrodynamics:coil')
    event.replaceInput({input: 'createaddition:copper_rod'}, 'createaddition:copper_rod', 'minecraft:copper_ingot')
    event.replaceInput({input: 'createaddition:electrum_ingot'}, 'createaddition:electrum_ingot', 'immersiveengineering:ingot_electrum')
    event.replaceInput({input: 'createaddition:iron_wire'}, 'createaddition:iron_wire', 'electrodynamics:wireiron')
    event.remove({id: 'createaddition:liquid_burning/biofuel'})
    event.remove({output: 'createaddition:copper_spool'})
    event.remove({output: 'createaddition:electrum_ingot'})
    event.remove({output: 'createaddition:electrum_amulet'})
    event.remove({output: 'createaddition:electrum_sheet'})
    event.remove({output: 'createaddition:zinc_sheet'})
    event.remove({output: 'createaddition:iron_wire'})
    event.remove({output: 'createaddition:gold_wire'})
    event.remove({output: 'createaddition:electrum_wire'})
    event.remove({output: 'createaddition:spool'})
    event.remove({output: 'createaddition:gold_spool'})
    event.remove({output: 'createaddition:electrum_spool'})
    event.remove({output: 'createaddition:copper_rod'})
    event.remove({output: 'createaddition:iron_rod'})
    event.remove({output: 'createaddition:gold_rod'})
    event.remove({output: 'createaddition:electrum_rod'})
    event.remove({output: 'createaddition:brass_rod'})
    event.remove({output: 'createaddition:rolling_mill'})
    event.remove({output: 'createaddition:large_connector'})
    event.remove({output: 'createaddition:redstone_relay'})
    event.remove({output: 'createaddition:barbed_wire'})
    event.remove({output: 'createaddition:tesla_coil'})
    event.remove({output: 'createaddition:seed_oil_bucket'})
    event.remove({output: 'createaddition:bioethanol_bucket'})
    event.remove({output: 'createaddition:copper_wire'})
    event.replaceInput({input: "createaddition:capacitor",},
        "createaddition:capacitor",
        "immersiveengineering:electron_tube"
    )

  
})

