ServerEvents.recipes(event => {
        
        event.remove({output: `electrodynamics:ingotstainlesssteel`})
        event.remove({output: `electrodynamics:creativepowersource`})
        event.remove({output: `electrodynamics:creativefluidsource`})
        event.remove({output: `electrodynamics:railgunkinetic`})
        event.remove({output: `electrodynamics:railgunplasma`})
        event.remove({output: `electrodynamics:electricbaton`})
        event.remove({output: `electrodynamics:mechanizedcrossbow`})
        event.remove({output: `electrodynamics:fermentationplant`})
        event.remove({type: `electrodynamics:mineral_crusher_recipe`})
        event.remove({output: `electrodynamics:mineralcrusher`})
        event.remove({type: `electrodynamics:mineralcrusherdouble`})
        event.remove({type: `electrodynamics:mineralcrushertriple`})
        event.remove({type: `electrodynamics:mineral_grinder_recipe`})
        event.remove({id: `electrodynamics:gunpowder`})
        event.remove({output: `electrodynamics:coalcoke`})
        event.remove({output: `electrodynamics:circuitbasic`})
        event.remove({output: `electrodynamics:circuitadvanced`})
        event.remove({output: `electrodynamics:circuitelite`})
        event.remove({output: `electrodynamics:circuitultimate`})
        event.remove({output: `electrodynamics:jetpack`})
        event.remove({output: `electrodynamics:rodsteel`})
        event.remove({output: `electrodynamics:nuggetsteel`})
        event.remove({output: `electrodynamics:ingotsteel`})
        event.remove({output: `electrodynamics:ingotvanadiumsteel`})
        event.remove({output: `electrodynamics:ingotstainlesssteel`})
        event.remove({output: `electrodynamics:ingottitaniumcarbide`})
        event.remove({output: `electrodynamics:rodtitaniumcarbide`})
        event.remove({output: `electrodynamics:rodhslasteel`})
        event.remove({output: `electrodynamics:rodstainlesssteel`})
        event.remove({output: `electrodynamics:nuggetstainlesssteel`})
        event.remove({output: `electrodynamics:nuggethslasteel`})
        event.remove({output: `electrodynamics:nuggettitaniumcarbide`})
        event.remove({output: `electrodynamics:nuggetsuperconductive`})
        event.remove({output: `electrodynamics:ingotaluminum`})
        event.remove({output: `electrodynamics:drillheadhslasteel`})
        event.remove({output: `electrodynamics:drillheadsteel`})
        event.remove({output: `electrodynamics:drillheadstainlesssteel`})
        event.remove({output: `electrodynamics:drillheadtitanium`})
        event.remove({output: `electrodynamics:drillheadtitaniumcarbide`})
        event.remove({id: `electrodynamics:gear_iron`})
        event.remove({id: `electrodynamics:gear_copper`})
        event.remove({id: `electrodynamics:gear_tin`})
        event.remove({id: `electrodynamics:gear_netherite`})
        event.remove({id: `electrodynamics:gear_bronze`})
        event.remove({output: `electrodynamics:platebronze`})
        event.remove({output: `electrodynamics:ceramic_plate`})
        event.remove({id: `electrodynamics:blasting/steel_ingot_from_iron`})
        event.remove({id: `electrodynamics:plate_bronze`})
        event.remove({id: `electrodynamics:gear_steel`})
        event.remove({output: `electrodynamics:ingotbronze`, type: 'electrodynamics:energized_alloyer_recipe'})
        event.remove({output: `electrodynamics:ingotbronze`, type: 'electrodynamics:reinforced_alloyer_recipe'})
        event.remove({output: `electrodynamics:ingotbronze`, type: 'immersiveengineering:arc_furnace'})
        event.remove({output: `electrodynamics:netherite_ingot`, type: 'electrodynamics:energized_alloyer_recipe'})
        event.remove({output: `electrodynamics:netherite_ingot`, type: 'electrodynamics:reinforced_alloyer_recipe'})
        event.remove({output: `electrodynamics:platecopper`})
        event.remove({output: `electrodynamics:plateiron`})
        event.remove({output: `electrodynamics:platesteel`})
        event.remove({output: `electrodynamics:platelead`})
        event.remove({output: `electrodynamics:platealuminum`})
        event.remove({output: 'electrodynamics:mineralcrusher'})
        event.remove({output: 'electrodynamics:mineralcrusherdouble'})
        event.remove({output: 'electrodynamics:mineralcrushertriple'})
        event.remove({output: 'electrodynamics:electricbaton'})
        event.remove({output: 'electrodynamics:railgunplasma'})
        event.remove({output: 'electrodynamics:mechanizedcrossbow'})
        event.remove({output: 'electrodynamics:fermentationplant'})
        event.remove({output: 'electrodynamics:nugettin'})
        event.remove({output: 'electrodynamics:rodsteel'})
        event.remove({output: 'electrodynamics:drillheadsteel'})
        event.remove({output: 'electrodynamics:electricdrill'})
        

    
    event.replaceOutput(
	{output: 'electrodynamics:ingotsteel'},
	'electrodynamics:ingotsteel',
	'immersiveengineering:ingot_steel'
)
})