ServerEvents.recipes(event => {
    const ed = "electrodynamics"
    
    event.remove({output: `immersiveengineering:chemthrower`})
    event.remove({output: `immersiveengineering:bullet_buckshot`})
    event.remove({output: `immersiveengineering:bullet_he`})
    event.remove({output: `immersiveengineering:bullet_armor_piercing`})
    event.remove({output: `immersiveengineering:bullet_dragons_breath`})
    event.remove({output: `immersiveengineering:bullet_homing`})
    event.remove({output: `immersiveengineering:bullet_wolfpack`})
    event.remove({output: `immersiveengineering:toolupgrade_chemthrower_focus`})
    event.remove({output: `immersiveengineering:toolupgrade_chemthrower_multitank`})
    event.remove({output: `immersiveengineering:turret_gun`})
    event.remove({output: `immersiveengineering:turret_chem`})
    event.remove({output: `immersiveengineering:bullet_flare`})
    event.remove({output: `immersiveengineering:dust_nickel`})
    event.remove({output: `immersiveengineering:railgun`})
    event.remove({output: `immersiveengineering:nugget_copper`})
    event.remove({output: `immersiveengineering:dust_copper`})
    event.remove({output: `immersiveengineering:dust_iron`})
    event.remove({output: `immersiveengineering:dust_steel`})
    event.remove({output: `immersiveengineering:dust_lead`})
    event.remove({output: `immersiveengineering:dust_aluminum`})
    event.remove({output: `immersiveengineering:dust_silver`})
    event.remove({output: `immersiveengineering:dust_gold`})
    event.remove({output: `immersiveengineering:graphite_electrode`})
    event.remove({output: `${ed}:raw_composite_plating`})
    event.remove({id: 'immersiveengineering:crusher/graphite_ingot'})
    event.remove({id: 'immersiveengineering:crusher/red_sandstone'})
    event.remove({id: 'immersiveengineering:crusher/sandstone'})
    event.remove({id: 'immersiveengineering:crafting/stick_netherite'})
    event.remove({id: 'immersiveengineering:crafting/stick_aluminum'})
    event.remove({id: 'immersiveengineering:crafting/stick_iron'})
    event.remove({id: 'immersiveengineering:crafting/stick_steel'})
    event.remove({output: `immersiveengineering:stick_steel`})
    event.remove({output: `immersiveengineering:stick_iron`})
    event.remove({output: `immersiveengineering:stick_aluminum`})
    event.remove({output: `immersiveengineering:stick_netherite`})
    event.remove({id: 'immersiveengineering:crafting/fertilizer'})
    event.remove({output: `immersiveengineering:drill`})
    event.remove({id: 'immersiveengineering:crafting/plate_iron_hammering'})
    event.remove({id: 'immersiveengineering:crafting/plate_silver_hammering'})
    event.remove({id: 'immersiveengineering:crafting/plate_aluminum_hammering'})
    event.remove({id: 'immersiveengineering:crafting/plate_gold_hammering'})
    event.remove({id: 'immersiveengineering:crafting/plate_steel_hammering'})
    event.remove({id: 'immersiveengineering:crafting/plate_electrum_hammering'})
    event.remove({id: 'immersiveengineering:crafting/plate_uranium_hammering'})
    event.remove({id: 'immersiveengineering:crafting/plate_copper_hammering'})
    event.remove({id: 'immersiveengineering:crafting/plate_nickel_hammering'})
    event.remove({id: 'immersiveengineering:crafting/plate_lead_hammering'})
    event.remove({id: 'immersiveengineering:crafting/plate_constantan_hammering'})
    event.remove({id: 'immersiveengineering:crafting/empty_casing'})
    event.remove({id: 'immersiveengineering:metalpress/rod_electrum'})
    event.remove({id: 'immersiveengineering:metalpress/rod_copper'})
    event.remove({id: 'immersiveengineering:metalpress/rod_gold'})
    event.remove({id: 'immersiveengineering:metalpress/rod_brass'})
    event.remove({id: 'immersiveengineering:metalpress/plate_zinc'})
    event.remove({id: 'immersiveengineering:crafting/drillhead_iron'})
    event.remove({id: 'immersiveengineering:crafting/drillhead_steel'})
    event.remove({output: `immersiveengineering:drillhead_iron`})
    event.remove({output: `immersiveengineering:drillhead_steel`})
    event.remove({output: `immersiveengineering:ingot_steel`, type: 'electrodynamics:energized_alloyer_recipe'})
    event.remove({output: `create:brass_ingot`, type: 'immersiveengineering:arc_furnace'})
    event.remove({output: `immersiveengineering:ingot_constantan`, type: 'immersiveengineering:arc_furnace'})
    event.remove({output: `immersiveengineering:ingot_electrum`, type: 'immersiveengineering:arc_furnace'})
    event.remove({output: `immersiveengineering:fiberboard`})
    event.remove({id: `immersiveengineering:fermenter/glow_berries`})
    event.remove({output: 'immersiveengineering:mold_wire'})

    event.replaceInput({input: 'immersiveengineering:nugget_electrum'},
        'immersiveengineering:nugget_electrum',
        '#c:nuggets/electrum'
        )
})